language: clojure
lein: lein2
jdk:
  - oraclejdk7
  - oraclejdk8
cache:
  directories:
    - $HOME/.lein
    - $HOME/.m2
install:
  - wget https://b25518159d104e8997f8-d5f47ab458856b6ee0c2780ddf5e291c.ssl.cf5.rackcdn.com/libsodium-1.0.11_amd64.deb
  - sudo dpkg -i libsodium-1.0.11_amd64.deb
script:
  - lein with-profile +test cljfmt check
  - lein with-profile +test kibit
  - lein with-profile +test eastwood
  - lein test

after_success:
  - CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein with-profile +test cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
